# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from control/EncoderData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class EncoderData(genpy.Message):
  _md5sum = "23ea1aec3b3aed5da94835b8bde1468c"
  _type = "control/EncoderData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 en_ext1
float32 en_ext2
float32 en_ext3
float32 en_in1
float32 en_in2
float32 en_in3
float32 en_in4
"""
  __slots__ = ['en_ext1','en_ext2','en_ext3','en_in1','en_in2','en_in3','en_in4']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       en_ext1,en_ext2,en_ext3,en_in1,en_in2,en_in3,en_in4

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EncoderData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.en_ext1 is None:
        self.en_ext1 = 0.
      if self.en_ext2 is None:
        self.en_ext2 = 0.
      if self.en_ext3 is None:
        self.en_ext3 = 0.
      if self.en_in1 is None:
        self.en_in1 = 0.
      if self.en_in2 is None:
        self.en_in2 = 0.
      if self.en_in3 is None:
        self.en_in3 = 0.
      if self.en_in4 is None:
        self.en_in4 = 0.
    else:
      self.en_ext1 = 0.
      self.en_ext2 = 0.
      self.en_ext3 = 0.
      self.en_in1 = 0.
      self.en_in2 = 0.
      self.en_in3 = 0.
      self.en_in4 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7f().pack(_x.en_ext1, _x.en_ext2, _x.en_ext3, _x.en_in1, _x.en_in2, _x.en_in3, _x.en_in4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.en_ext1, _x.en_ext2, _x.en_ext3, _x.en_in1, _x.en_in2, _x.en_in3, _x.en_in4,) = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7f().pack(_x.en_ext1, _x.en_ext2, _x.en_ext3, _x.en_in1, _x.en_in2, _x.en_in3, _x.en_in4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.en_ext1, _x.en_ext2, _x.en_ext3, _x.en_in1, _x.en_in2, _x.en_in3, _x.en_in4,) = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7f = None
def _get_struct_7f():
    global _struct_7f
    if _struct_7f is None:
        _struct_7f = struct.Struct("<7f")
    return _struct_7f
